### ISSUE TITLE
Add counts to state filters

### ISSUE THREAD

**Issue by damianr** [holaplex/marketplace#100]
As a user I want to see as count of how many NFTs are in each state so I can know what to expect.

**Comment by damianr** [comment]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/260165/158219338-4bcf7fdd-7b27-427b-b4b5-3ccab7ebb8e9.png">

**Comment by kespinola** [comment]
I'm some what concerned on the performance implications of these counts. make sure to try out the queries in sql before we write the code.

Query wise thinking something like

```
marketplace(subdomain: "") {
  counts(address: "current_user_address") {
    listed
    unlisted
    owned
  }
}
```

Same layout for collection aka creator scope.

**Comment by alchemistgo87** [comment]
@kespinola Should not 'counts' be a separate query similar to nfts() query, something like this:

count(
owners: [PublicKey!]
creators: [PublicKey!]
listed: [PublicKey!]
offerers: [PublicKey!]
): {
    listed
    unlisted
    owned
    offered
}

**Comment by kespinola** [comment]
```
marketplace(subdomain: "") {
  counts(
    wallet: PublicKey!
    creators: [PublicKey!]
  ): {
      all
      listed
      owned
      offered
  }
}
```

You're right we'll want to do creators but i still think scoping under marketplace is the move since you'll want access to it for the counts.

Doesn't need listed or attributes since these will just be based on the preset filters.

**Comment by kespinola** [comment]
We should also return a list of counts for the marketplace grouped by the auction house. marketplaces are going to be multi mint shortly anywhere we work with a singular auction house needs to be multiple.

**Comment by kespinola** [comment]
done.
