### ISSUE TITLE
Multiple Collection Filters not working properly

### ISSUE THREAD

**Issue by dandlezzz** [holaplex/marketplace#101]
Multiple collection filters don't work properly. checkout junglecats.  The URL doesn't match the filtered set.

<img width="857" alt="image" src="https://user-images.githubusercontent.com/5935947/158220818-0a26416f-179b-41fa-ad8a-132b3b062560.png">

**Comment by kespinola** [comment]
Sorry. have this set to store owner. Fixed in branch I have.
