### ISSUE TITLE
Add background color to logo

### ISSUE THREAD

**Issue by damianr** [holaplex/marketplace#102]
If someone uses a PNG with transparent background for the logo the banner image is visible behind it. Need to add background color to match the main site background color to the logo container.

**Comment by damianr** [comment]
<img width="247" alt="image" src="https://user-images.githubusercontent.com/260165/158225982-d7ae2485-3c9f-4778-881e-56f0933966e0.png">

**Comment by damianr** [comment]
Also noticing that the image is scaled to fit the 1:1 ratio. We should have a container div wrapping the image and then set the image to object-fit: cover

**Comment by kespinola** [comment]
done.
