### ISSUE TITLE
Show avatars and twitter names for pubkeys

### ISSUE THREAD

**Issue by dandlezzz** [holaplex/marketplace#103]
## Goal
All user owned wallet addresses are potentially enriched with twitter information when handle connected to bonfida.

## Requirements

Any object currently tracking a user wallet address should now return wallet objects which have a field of profile.
```graphql
type TwitterProfile {
  avatarUrl: Image
  bannerUrl: Image
  handle: String
}

type Wallet {
  address: PublicKey
  profile: TwitterProfile
}

type Nft {
  creators: [Wallet]
  owner: Wallet
}
```

The data loader for twitter_profiles should batch by PublicKey<Wallet> and leverage the twitter_handles table to match the address with a twitter handle. If a twitter handle is present query the twitter API for user avatarUrl and bannerUrl. The requests are already being doin by the profile root query.

## Blockers

- [X] [indexing task](https://github.com/holaplex/solana-indexer/issues/218)

**Comment by damianr** [comment]
Any place we are displaying a wallet address we should display the logo and twitter handle when we have that info. If the wallet isn't connected to twitter display the default gradient logo with the wallet address.

Also add creator to the NFT card and link to the creator page in the marketplace.

![image](https://user-images.githubusercontent.com/260165/162339386-6f8c760d-a52c-48cb-92ce-65d0979a536c.png)

If an NFT has multiple creators just display the logos for them to keep it to 1 row

![image](https://user-images.githubusercontent.com/260165/162339402-db0b46c0-44da-4984-b46f-4cc464ab804c.png)
