### ISSUE TITLE
multi-creator support

### ISSUE THREAD

**Issue by damianr** [holaplex/marketplace#107]
UX around displaying and filtering by creator needs serious help. 

Display preview of the NFTs available by the creator. This can be a random selection or some other way of grabbing the NFTs depending on what we can do. 

https://www.figma.com/file/eACyDSbpcWYoE9ypOZNlf8/DAO-Marketplace?node-id=1008%3A27178

**Comment by kespinola** [comment]
https://github.com/holaplex/marketplace/pull/119
done.
