### ISSUE TITLE
Configure Marketplace Supported Tokens

### ISSUE THREAD

**Issue by damianr** [holaplex/marketplace#111]
As a marketplace owner I want to offer SPL tokens as additional or only payment method for my customers so I can strengthen my project’s tokenomics

### Questions

- Will we need multiple AH for a MP?
- How many SPL tokens could a MP support?
- Assume that we would allow only an SPL token and no SOL?
- Can we give listers the ability to list an NFT for any of the supported tokens?
- Where is the info on the SPL tokens stored? / How would a MP owner add a token?
- Will we have a logo or icon for the tokens?

### Design considerations

- Admin UI needed
    - Select (add?) tokens accepted on the marketplace
    - Select default token for marketplace if there are multiple (the token the offer and buy now forms default to)
- Customer UI needed
    - Select token to pay with in offer and buy now forms
    - Choose tokens to accept for a particular listing (?)
- Analytics
- Need to show token in activity

The auction-house contract supports alternative SPL token mints. What would it take for marketplaces to run sales in various SPL tokens? Assuming the contract needs no changes, what changes do we need to make to the indexer, graphql and client?

## Screenshots

<img width="789" alt="Screen Shot 2022-04-29 at 8 43 40 AM" src="https://user-images.githubusercontent.com/2388118/165896377-94d804bd-6be8-4d81-af81-11f3b8273b05.png">

**Comment by dandlezzz** [comment]
@damianr How will we handle analytics for multi mint marketplaces?

**Comment by damianr** [comment]
We need to figure some things out before I can start working on that. Need to know if there will be multiple tokens supported, and if so if there will or can be a notion of a default token for the marketplace. I'll put something on the cal this week for you, kyle, ryan and I to kick this puppy off.

**Comment by dandlezzz** [comment]
@damianr gonna assign this to you as we work on mocks.
