### ISSUE TITLE
Add basic analytics

### ISSUE THREAD

**Issue by dandlezzz** [holaplex/marketplace#112]
• Show analytics at the root level of the marketplace that are for all NFTs available.
• Show analytics specific to a creator when viewing their specific page.

https://www.figma.com/file/eACyDSbpcWYoE9ypOZNlf8/DAO-Marketplace?node-id=1008%3A27178

**Comment by damianr** [comment]
@dandlezzz if possible would be nice to have a "default token" for multi spl token marketplaces, that would help here. But we need to figure out the plan for spl support first.

**Comment by kespinola** [comment]
done.
