### ISSUE TITLE
Hide creator in sidebar if single creator MP

### ISSUE THREAD

**Issue by dandlezzz** [holaplex/marketplace#113]
See cityshop.holaplex.market vs junglecats.holaplex.market. We don't need to show the creators pick'em when only one item is in it.

<img width="428" alt="image" src="https://user-images.githubusercontent.com/5935947/159289685-c591195b-338e-4037-9ddf-5bbf5bba415c.png">

**Comment by alchemistgo87** [comment]
@dandlezzz Right now we are not showing creators at all in the sidebar of collection page.

**Comment by dandlezzz** [comment]
Ahh, someone must've beat you to it.
