### ISSUE TITLE
View Sales History

### ISSUE THREAD

**Issue by kespinola** [holaplex/marketplace#114]
## Goal
Users can see the previous sales history of an NFT.

## Requirements
- Query any purchase receipts for the NFT based on its mint address.
- Show purchase receipts in activity area of NFT.

![Screen Shot 2022-02-07 at 11 52 42 AM](https://user-images.githubusercontent.com/2388118/152861467-19703528-e163-4b20-bbba-aed20c467c68.png)

**Comment by alchemistgo87** [comment]
@damianr Can you help with the u-turn arrow icon in this:
![Screenshot 2022-03-25 at 12 45 37 PM](https://user-images.githubusercontent.com/1254443/160072823-f9508122-9eeb-486d-9de3-83d154171cca.png)

**Comment by damianr** [comment]
@alchemistgo87 Here ya go!
![arrow](https://user-images.githubusercontent.com/260165/160179478-927691a8-8491-40a2-8536-93baf8f58c1b.svg)

**Comment by kespinola** [comment]
https://github.com/holaplex/marketplace/pull/135

done
