### ISSUE TITLE
Outstanding List after purchase

### ISSUE THREAD

**Issue by dandlezzz** [holaplex/marketplace#127]
If I list my NFT for 1 SOL and then someone makes an offer for .5 SOL, when I accept their offer. The original listing still shows up on that NFTs details page.

repro instructions:
List for X SOL
Offer for Y SOL
Accept offer.

What should happen?
If a user accepts the offer, their listing is no longer valid. We should cancel the listing. The same user accepting the offer will be the one who made the listing.

**Comment by kespinola** [comment]
done https://github.com/holaplex/marketplace/pull/150
