### ISSUE TITLE
Non square logos are not displaying properly

### ISSUE THREAD

**Issue by damianr** [holaplex/marketplace#141]
Favicon and the button on the nft details page/creator page are squished on the jungle cats mp.

**Comment by damianr** [comment]
<img width="189" alt="image" src="https://user-images.githubusercontent.com/260165/159981154-d7731587-502d-4903-b0fe-14b2634e13d9.png">

**Comment by alchemistgo87** [comment]
@damianr Desktop Browsers does not support non-square favicons, so non-square favicons will remain squished. But the squished logo issue has been fixed in #154

**Comment by damianr** [comment]
Oh ok makes sense. I'll make another ticket to handle this on upload. Seems like we should crop the logo to square.
