### ISSUE TITLE
Sort "All" filter by listed first

### ISSUE THREAD

**Issue by damianr** [holaplex/marketplace#145]
When viewing All nfts in either the home page of a marketplace or the creator/collection page we should display the listed NFTs in the list first.

**Comment by dandlezzz** [comment]
@damianr I got this piece of feedback from one of our marketplace users.

```cosimo_rip — Today at 7:05 AM
I imagine this is on your radar already, but sort by listing price (low to high) keeps coming up as a feature request```

**Comment by damianr** [comment]
@dandlezzz yeah we have a [ticket for this](https://github.com/holaplex/marketplace/issues/132). This one was just a default sort to make that list a little more useful.
