### ISSUE TITLE
Detailed analytics and activity

### ISSUE THREAD

**Issue by damianr** [holaplex/marketplace#158]
https://www.figma.com/file/eACyDSbpcWYoE9ypOZNlf8/DAO-Marketplace?node-id=1001%3A26743

**Comment by damianr** [comment]
@alchemistgo87 let me know if you have any questions about this one!

**Comment by alchemistgo87** [comment]
@damianr First of all, the design looks very good and useful too!

Here are a few questions I have right now:
- Which graph needs to be shown on the main page (Floor price graph or average price graph)
- Do you have any suggestions for the graph design library we can use for this one.
- On the details and activity page, are we supposed to show all the activities at once or should there be an element of pagination.

**Comment by damianr** [comment]
@alchemistgo87 Glad you like them!

- Let's start with floor price for the graph
- [This library seems pretty cool.](https://airbnb.io/visx/areas) Looks like they have a graph type that should work well for this. 
- Ideally we'd show all activity and use an infinite scroll for the NFT details page activity and this one.

**Comment by alchemistgo87** [comment]
@damianr 

Do we need to show more options on click of 'Last 7 Days'?

![Screenshot 2022-04-04 at 4 50 13 PM](https://user-images.githubusercontent.com/1254443/161533498-003196fe-af9b-4078-8e59-3722931b7918.png)

**Comment by alchemistgo87** [comment]
@kespinola Can you verify this:

Notes on apis update required for this task:

In marketplace query we need to add:

```
stats {
  floorPrice
  avgPrice
  volAllTime
  vol24hr
  floorPriceData(daysCount: Int): [PricePoint!]!
  avgPriceData(daysCount: Int): [PricePoint!]! 
}

activities: [NftActivity!]!

```
where PricePoint will be structured as:

```
PricePoint {
  price: Volume
  date: DateTimeUtc
}
```

**Comment by damianr** [comment]
@alchemistgo87 yes options should be "last 7 days", "last 30 days", and "all time"

**Comment by alchemistgo87** [comment]
@damianr Do we have any particular design for this filter popup or any reference for this on holaplex site?

**Comment by kespinola** [comment]
@alchemistgo87 what do you think of 

```graphql
auctionHouse {
  charts(startDate: DateTime, endTime: DateTime) {
    floorPrice {
      date
      price
    }
  }
}
```

**Comment by damianr** [comment]
@alchemistgo87 You can use the same design for the options drop down on holaplex.com for About and Help. Not the label, that should stay the same as it is in the design but the menu itself. 
<img width="374" alt="image" src="https://user-images.githubusercontent.com/260165/161594457-1683216d-3671-4496-a01a-5df25cc5e887.png">

**Comment by kespinola** [comment]
done.
