### ISSUE TITLE
Filter and Display NFTs Listed with Alt SPL Token on Home and Creator Pages

### ISSUE THREAD

**Issue by kespinola** [holaplex/marketplace#197]
## Goal

- Users are aware of the token used for sale of an NFT when filtering from the marketplace home or creator pages.
- Users can filter nfts by the token used to list the NFT.

**Comment by kespinola** [comment]
@damianr can we get some guidance on how the list views should look when using multiple spl tokens? Do you want filters for the tokens?

**Comment by damianr** [comment]
Good point yeah I'll get some design for this.

**Comment by damianr** [comment]
When "Current listings" is selected and there are multiple SPL tokens supported show the tokens with checkboxes to filter by token. 

![Image](https://user-images.githubusercontent.com/260165/166077040-98fb5f19-7198-4d99-aafc-1c0ffa25fa15.png)

**Comment by damianr** [comment]
https://www.figma.com/file/eACyDSbpcWYoE9ypOZNlf8/Marketplaces?node-id=1351%3A16000
