### ISSUE TITLE
Marketplace Supported Token Analytics

### ISSUE THREAD

**Issue by kespinola** [holaplex/marketplace#202]
## Goal

When viewing analytics for a marketplace users can switch between the different tokens supported by the marketplace.

<img width="742" alt="Screen Shot 2022-04-28 at 6 09 53 PM" src="https://user-images.githubusercontent.com/2388118/165796825-fc60806a-88f5-4480-b539-acedf29707e8.png">

<img width="1319" alt="Screen Shot 2022-04-28 at 6 11 34 PM" src="https://user-images.githubusercontent.com/2388118/165797115-ca15c2a7-35f0-4ce1-9188-dfc9d0b22032.png">

**Comment by kespinola** [comment]
@damianr can you provide some guidance on how this should work for multiple tokens? Assuming we have a dropdown at the top that lets the user switch between the tokens. 

Some light mockups here would be helpful. Ty.

**Comment by damianr** [comment]
Yeah on my list.

**Comment by damianr** [comment]
@kespinola 
- On the summery on the home and creator pages just show the token with the most transactions on the marketplace. 
- On the activity page show a drop down to display analytics and activity for the selected token, default to the token with the most transactions on the marketplace
- Add link in the header for "Activity"


![Image](https://user-images.githubusercontent.com/260165/166077622-def17c4f-5aa6-4ca2-9354-571628580445.png)



![Image](https://user-images.githubusercontent.com/260165/166077639-560d9829-ea69-43c1-83a2-5e7c0c3df9ed.png)




https://www.figma.com/file/eACyDSbpcWYoE9ypOZNlf8/Marketplaces?node-id=1351%3A16000
