### ISSUE TITLE
List NFT for Sale

### ISSUE THREAD

**Issue by kespinola** [holaplex/marketplace#3]
## Goal
Owners of an NFT supported by the marketplace can put it up for buy now sale through the auction house representing the marketplace on chain.

## Requirements
- The owner of the NFT has option to list for sale.
- Clicking list for sale routes to `/nfts/{address}/listings/new`. (nested view already in dev)

![Screen Shot 2022-02-07 at 11 35 55 AM](https://user-images.githubusercontent.com/2388118/152859138-24669818-85fb-409a-8ddb-6338153bf9e8.png)

**Comment by dandlezzz** [comment]
See this file for instruction requirements https://github.com/holaplex/metaplex-program-library/blob/master/auction-house/js/src/generated/instructions/sell.ts

**Comment by kespinola** [comment]
done.
