### ISSUE TITLE
Edit marketplaces

### ISSUE THREAD

**Issue by kespinola** [holaplex/marketplace#61]
## Goal

Marketplace owners can update their marketplace.

### Requirements
- Update marketplace banner, logo, description, and title.
- Add/remove creators from marketplace.

https://www.figma.com/file/eACyDSbpcWYoE9ypOZNlf8/DAO-Marketplace?node-id=839%3A27608

**Comment by alchemistgo87** [comment]
@kespinola Are we also going to save logo and banner images to ipfs or does that have to be saved to arweave?

**Comment by alchemistgo87** [comment]
@kespinola Where should we send the user on click of "contact us" link here:
![Screenshot 2022-03-11 at 8 47 33 PM](https://user-images.githubusercontent.com/1254443/157895427-5f062a13-6335-48b7-ba64-648c57ec446b.png)

**Comment by kespinola** [comment]
> @kespinola Are we also going to save logo and banner images to ipfs or does that have to be saved to arweave? 

Save everything to IPFS. 

> Also, how should we update Transaction Fees in the Marketplace data.
That is a updateAuctionHouse instruction from mpl-auction-house

> Where should we send the user on click of "contact us" link here:
@damianr what should this link do?

**Comment by kespinola** [comment]
done.
