### ISSUE TITLE
NFT Card with Offers

### ISSUE THREAD

**Issue by damianr** [holaplex/marketplace#89]
Display an icon on the NFT card in the list to give some visual cue that there are offers on an NFT.

**Comment by damianr** [comment]
<img width="308" alt="image" src="https://user-images.githubusercontent.com/260165/157713664-ea3fa56c-e128-4cc1-8233-a57d43f50d16.png">

**Comment by bellebellesol** [comment]
Solution: 
- If NFT has offers, show offer chip only while hovering the card
- Update expand view button to the same style as offer chip

Default state:
<img width="396" alt="Screen Shot 2022-03-11 at 10 01 40 am" src="https://user-images.githubusercontent.com/95664179/157890004-9552075b-1324-453e-8a3b-62c32e5e6aa1.png">

Hover state:
<img width="436" alt="Screen Shot 2022-03-11 at 10 01 16 am" src="https://user-images.githubusercontent.com/95664179/157890056-638d79e1-fe5d-4863-96fc-ce37a366bc4c.png">

**Comment by damianr** [comment]
@bellebellesol I think we should show the chip even when user isn't hovering. We want to call these out while scanning the list.

**Comment by bellebellesol** [comment]
Ok yeah, good point. I'll update the ticket now.
