### ISSUE TITLE
banner size is too large for mobile

### ISSUE THREAD

**Issue by dandlezzz** [holaplex/marketplace#92]
1500x350 wont work on mobile. maybe we collect multiile assets

**Comment by damianr** [comment]
Let's reduce height for banner on mobile. Height for mobile banner in design system is 10.5 rem.

**Comment by kespinola** [comment]
![Screen Shot 2022-03-31 at 4 06 25 PM](https://user-images.githubusercontent.com/2388118/161163808-ba80ebec-dcc2-4087-af0d-75e5a9a2906a.png)

width based breakpoints in place to reduce the height of the banner on smaller screens.
